name: Security CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint bandit safety

    - name: Run Pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Run Bandit (Security Analysis)
      run: |
        bandit -r . -x tests -f html -o bandit-report.html

    - name: Run Safety (Check for insecure dependencies)
      run: |
        safety check --full-report --output safety-report.json

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: bandit-report.html

    - name: Upload Safety Report
      uses: actions/upload-artifact@v2
      with:
        name: safety-report
        path: safety-report.json
